"""add unique index on enroll slot

Revision ID: 20a47de2f3f7
Revises: 
Create Date: 2025-12-11 16:41:32.376364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a47de2f3f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_service_enrolls_date_slot', 'service_enrolls', ['service_date_id', 'slot_time'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_service_enrolls_date_slot', table_name='service_enrolls')
    # ### end Alembic commands ###
