"""fixed accountcreated 1to1 user and accound and created relationship for account and service

Revision ID: 22760cb69ede
Revises: 4dac59cd1a93
Create Date: 2026-01-03 12:56:06.580523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22760cb69ede'
down_revision: Union[str, Sequence[str], None] = '4dac59cd1a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('account_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'services', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###
