"""add_service_chat_and_support_chat_models

Revision ID: 2a458c7c4854
Revises: 371fc840134a
Create Date: 2025-12-23 23:12:02.699806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a458c7c4854'
down_revision: Union[str, Sequence[str], None] = '371fc840134a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_chats',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('support_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['support_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_support_chats_client_support', 'support_chats', ['client_id', 'support_id'], unique=True)
    op.create_table('service_chats',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['master_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_service_chats_master_client_service', 'service_chats', ['master_id', 'client_id', 'service_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_service_chats_master_client_service', table_name='service_chats')
    op.drop_table('service_chats')
    op.drop_index('ux_support_chats_client_support', table_name='support_chats')
    op.drop_table('support_chats')
    # ### end Alembic commands ###
