"""add_payment_model

Revision ID: 371fc840134a
Revises: 20a47de2f3f7
Create Date: 2025-12-22 21:25:18.784384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371fc840134a'
down_revision: Union[str, Sequence[str], None] = '20a47de2f3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('enroll_id', sa.Integer(), nullable=True),
    sa.Column('yookassa_payment_id', sa.String(length=255), nullable=True),
    sa.Column('yookassa_status', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'succeeded', 'canceled', 'failed', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_url', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enroll_id'], ['service_enrolls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yookassa_payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
